# Generated by Django 5.1.6 on 2025-03-03 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "basal_rate",
                    models.DecimalField(decimal_places=2, default=1.2, max_digits=5),
                ),
                (
                    "correction_factor",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "glucose_target",
                    models.DecimalField(decimal_places=1, default=6.4, max_digits=4),
                ),
                (
                    "glucose_min",
                    models.DecimalField(decimal_places=1, default=3.9, max_digits=4),
                ),
                (
                    "glucose_max",
                    models.DecimalField(decimal_places=1, default=11.0, max_digits=5),
                ),
                (
                    "bolus_max",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("insulin_duration", models.IntegerField(default=240)),
                (
                    "iob",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "cob",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "max_iob",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
                ),
                ("em_enabled", models.BooleanField(default=False)),
                (
                    "diabetic_profile",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "carb_ratio",
                    models.DecimalField(decimal_places=1, default=10.0, max_digits=3),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlucoseReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reading", models.FloatField()),
                ("trend", models.CharField(max_length=6)),
                (
                    "basal_injected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "bolus_injected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glucose_readings",
                        to="api.userprofile",
                    ),
                ),
            ],
        ),
    ]
