# Generated by Django 5.1.6 on 2025-02-20 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = []
