# Generated by Django 5.1.6 on 2025-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="cob",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_bolus",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
