# Generated by Django 5.1.6 on 2025-02-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_adjusted_reading_glucosereading_reading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="basal_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1.2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bolus_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=15.0, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="carb_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=10.0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cob",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="correction_factor",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="glucose_max",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=11.0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="glucose_min",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=3.9, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="glucose_target",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=6.4, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="insulin_duration",
            field=models.IntegerField(blank=True, default=240, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="iob",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_iob",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=25.0, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="residual_iob",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
