# Generated by Django 5.1.6 on 2025-03-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_cob_userprofile_pending_bolus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='carb_ratio',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=4),
        ),
    ]
