# Generated by Django 5.1.6 on 2025-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20250220_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_update_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
