# Generated by Django 5.1.6 on 2025-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_auto_20250220_1628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
