# Generated by Django 5.1.6 on 2025-02-23 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_userprofile_last_update_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
