# Generated by Django 5.1.6 on 2025-02-23 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_userprofile_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="residual_iob",
        ),
    ]
