# Generated by Django 5.1.6 on 2025-02-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_basal_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diabetic_profile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
