# Generated by Django 5.1.6 on 2025-02-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_glucosereading_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glucosereading",
            name="reading",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
