# Generated by Django 5.1.6 on 2025-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_diabetic_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucosereading',
            name='basal_injected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='glucosereading',
            name='bolus_injected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='em_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_update_time',
            field=models.DateTimeField(default='2025-02-18 10:15:56'),
        ),
    ]
