# Generated by Django 5.1.6 on 2025-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_glucosereading_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glucosereading",
            name="reading",
            field=models.FloatField(),
        ),
    ]
