# Generated by Django 5.1.6 on 2025-02-28 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_glucosereading_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_update_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
