# Generated by Django 5.1.6 on 2025-03-01 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_glucosereading_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="readings",
        ),
    ]
