# Generated by Django 5.1.6 on 2025-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userprofile_readings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_update_time',
            field=models.DateTimeField(default='2025-02-18 20:47:22'),
        ),
    ]
