# Generated by Django 5.1.6 on 2025-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_userprofile_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_update_time',
            field=models.DateTimeField(default='1-01-01 00:00:00'),
        ),
    ]
