FROM python:3.12.9-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

ENV PYTHONPATH=/app

CMD ["celery", "-A", "backend.celery", "worker", "--loglevel=info"]
