[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn backend.wsgi:application -b 0.0.0.0:8000 -w 4
autostart=true
autorestart=true
stderr_logfile=/dev/fd/2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:daphne]
command=daphne -b 0.0.0.0 -p 8001 backend.asgi:application
autostart=true
autorestart=true
stderr_logfile=/dev/fd/2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
